version: '3.9'
services:
  api:
    build:
      context: ./apps/api
    environment:
      - ROBOROUTER_MINIO_ENDPOINT=minio:9000
      - ROBOROUTER_MINIO_ACCESS_KEY=admin
      - ROBOROUTER_MINIO_SECRET_KEY=adminadmin
      - ROBOROUTER_MINIO_SECURE=false
    ports:
      - "8000:8000"
    depends_on:
      - minio
  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

volumes:
  minio-data: {}


