stages:
  preprocess:
    cmd: echo "preprocess placeholder"
    deps: []
    outs:
      - data/processed
  train:
    cmd: echo "train placeholder"
    deps:
      - data/processed
    outs:
      - models
  ingest:
    cmd: python -m scripts.pipeline ingest
    deps: []
    outs: []
  registration:
    cmd: python -m scripts.pipeline registration
    deps: []
    outs: []
  segmentation:
    cmd: python -m scripts.pipeline segmentation
    deps: []
    outs: []
  change_detection:
    cmd: python -m scripts.pipeline change_detection
    deps: []
    outs: []
  report:
    cmd: python -m scripts.pipeline report
    deps: []
    outs: []

