# Default thresholds (override per profile in production)
ingest:
  sor_stddev_mult: 1.0
  voxel_size_m: 0.05
  intensity_min: 0.0
  intensity_max: 1.0

registration:
  icp_max_iters: 50
  icp_rmse_gate: 0.10
  voxel_down_m: 0.05
  robust_kernel: huber

segmentation:
  min_confidence: 0.6
  batch_size: 1

change_detection:
  min_voxel_size_m: 0.10
  min_points_per_voxel: 3

