name: CI

on:
  push:
    branches: [ develop ]
  pull_request:

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r apps/api/requirements.txt -r requirements-dev.txt
      - name: Lint
        run: ruff check apps/api
      - name: Types
        run: mypy apps/api
      - name: Tests
        run: pytest -q --cov=apps/api --cov-fail-under=70


