name: Security

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit
      - name: Audit API requirements
        run: |
          pip-audit -r apps/api/requirements.txt || true
          pip-audit -r requirements-dev.txt || true

